import { useEffect, useState } from "react";
import { Gauge, Link2 } from "lucide-react";
type ConfidenceData = {
  average: number | null;
  distribution: { high: number; medium: number; speculative: number };
  factors: Record<string, string | number>;
};
export default function ConfidencePage() {
  const [data, setData] = useState<ConfidenceData | null>(null);
  useEffect(() => { void fetch("/api/confidence", { cache: "no-store" }).then((r) => r.ok ? r.json() : null).then(setData); }, []);
  if (!data) return <div className="mx-auto max-w-[1100px]"><p className="text-sm text-muted-foreground">Loading confidence ledger…</p></div>;
  const pct = data.average == null ? "—" : `${Math.round(data.average * 100)}%`;
  return <div className="mx-auto max-w-[1100px]"><p className="lee-label text-primary">Epistemic health</p><h1 className="mt-2 text-3xl font-semibold">Confidence Propagation</h1><p className="mt-2 text-sm text-muted-foreground">Certainty degrades as Lee moves from evidence toward recommendations. Every step remains inspectable.</p><div className="mt-5 grid gap-3 sm:grid-cols-4"><div className="rounded-2xl border border-border bg-card p-4"><Gauge className="text-primary" size={18} /><p className="lee-label mt-3 text-muted-foreground">Average propagated</p><p className="mt-1 text-2xl font-semibold">{pct}</p></div><div className="rounded-2xl border border-border bg-card p-4"><p className="lee-label text-muted-foreground">High confidence</p><p className="mt-3 text-2xl font-semibold text-primary">{data.distribution.high}</p></div><div className="rounded-2xl border border-border bg-card p-4"><p className="lee-label text-muted-foreground">Medium</p><p className="mt-3 text-2xl font-semibold">{data.distribution.medium}</p></div><div className="rounded-2xl border border-border bg-card p-4"><p className="lee-label text-muted-foreground">Speculative</p><p className="mt-3 text-2xl font-semibold text-amber-600">{data.distribution.speculative}</p></div></div><section className="mt-5 rounded-2xl border border-border bg-card p-5"><p className="lee-label text-primary">Degradation factors</p><div className="mt-4 grid gap-3 sm:grid-cols-3">{Object.entries(data.factors).map(([step, factor]) => <div key={step} className="flex items-center justify-between rounded-xl bg-muted/50 p-3 text-sm"><span>{step.replaceAll("_", " ")}</span><span className="font-semibold text-primary">×{String(factor)}</span></div>)}</div></section><section className="mt-5 rounded-2xl border border-border bg-card p-5"><div className="flex items-center gap-2"><Link2 className="text-primary" size={17} /><div><p className="lee-label text-primary">Confidence chain</p><h2 className="mt-1 text-lg font-semibold">Lineage is available on every derived record</h2></div></div><p className="mt-3 text-sm text-muted-foreground">Observations, opportunities, simulations, and strategy objectives retain source IDs, step type, degradation factor, evidence count, and resulting confidence through the audit API.</p></section></div>;
}