import { useEffect, useState } from "react";
import { BookOpen, ThumbsDown, ThumbsUp } from "lucide-react";
const audiences = ["Founder", "Executive", "Investor", "Developer", "Technical", "Legal", "General"];
export default function ExplanationPage() {
  const [objects, setObjects] = useState<any[]>([]); const [objectId, setObjectId] = useState(""); const [audience, setAudience] = useState("Founder"); const [type, setType] = useState("object"); const [result, setResult] = useState<any>(null); const [busy, setBusy] = useState(false);
  useEffect(() => { void fetch("/api/internal/query", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ sources: ["universal_objects"], filters: {}, limit: 100, requester: "Explanation Console", purpose: "explanation_assembly" }) }).then((response) => response.ok ? response.json() : null).then((data) => { const rows = data?.results ?? []; setObjects(rows); if (rows[0]) setObjectId(rows[0].object_id); }); }, []);
  const generate = async () => { if (!objectId) return; setBusy(true); const response = await fetch("/api/explanations", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ objectId, audienceProfile: audience, explanationType: type, requester: "Explanation Console" }) }); if (response.ok) setResult(await response.json()); setBusy(false); };
  const feedback = async (value: string) => { if (result) await fetch(`/api/explanations/${result.id}/feedback`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ feedback: value }) }); };
  return <div className="mx-auto max-w-[1050px]"><p className="lee-label text-primary">Shared translation layer</p><h1 className="mt-2 text-3xl font-semibold">Explain Lee</h1><p className="mt-2 text-sm text-muted-foreground">Translate the same source-backed internal state for the person who needs to understand it.</p><section className="mt-6 rounded-2xl border border-border bg-card p-5"><div className="grid gap-4 md:grid-cols-3"><label className="text-xs font-semibold">Object<select value={objectId} onChange={(event) => setObjectId(event.target.value)} className="mt-2 h-10 w-full rounded-lg border border-border bg-background px-3 text-sm">{objects.map((item) => <option key={item.object_id} value={item.object_id}>{item.object?.name ?? item.object?.title ?? item.object_id}</option>)}</select></label><label className="text-xs font-semibold">Explanation type<select value={type} onChange={(event) => setType(event.target.value)} className="mt-2 h-10 w-full rounded-lg border border-border bg-background px-3 text-sm">{["object", "reasoning", "relationship", "timeline", "comparison", "risk"].map((item) => <option key={item}>{item}</option>)}</select></label><label className="text-xs font-semibold">Audience profile<select value={audience} onChange={(event) => setAudience(event.target.value)} className="mt-2 h-10 w-full rounded-lg border border-border bg-background px-3 text-sm">{audiences.map((item) => <option key={item}>{item}</option>)}</select></label></div><button onClick={() => void generate()} disabled={busy || !objectId} className="mt-5 rounded-xl bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground disabled:opacity-50">{busy ? "Assembling explanation…" : "Generate explanation"}</button></section>{result && <section className="mt-5 rounded-2xl border border-primary/30 bg-card p-6"><div className="flex items-start gap-3"><BookOpen className="mt-1 text-primary" size={20} /><div className="flex-1"><p className="lee-label text-primary">{result.audienceProfile} · {result.explanationType} · {Math.round(result.confidence * 100)}% confidence</p><p className="mt-3 text-base leading-7">{result.statement}</p><div className="mt-5 rounded-xl bg-muted/40 p-4"><p className="lee-label text-muted-foreground">Why this explanation</p>{result.whyChain?.map((step: any) => <p key={step.statement} className="mt-2 text-xs text-muted-foreground">• {step.statement}</p>)}</div><p className="mt-4 text-xs text-muted-foreground">Source records: {result.sourceObjectIds?.length ?? 0} · cached for reuse until source invalidation</p><div className="mt-4 flex gap-2"><button onClick={() => void feedback("good")} className="rounded-lg border border-border p-2 text-primary"><ThumbsUp size={15} /></button><button onClick={() => void feedback("needs_improvement")} className="rounded-lg border border-border p-2 text-muted-foreground"><ThumbsDown size={15} /></button></div></div></div></section>}</div>;
}