import { useEffect, useState } from "react";
import { CheckCircle2, Pencil, UserRound } from "lucide-react";
const labels: Record<string, string> = { thinkingStyle: "Thinking style", decisionStyle: "Decision style", writingVoice: "Writing voice", technicalDepth: "Technical depth", documentationPreferences: "Documentation preferences", riskTolerance: "Risk tolerance", currentGoals: "Current goals", currentPriorities: "Current priorities", energyPatterns: "Energy patterns", preferredModels: "Preferred models", favoriteWorkflows: "Favorite workflows", currentLearningGoals: "Current learning goals", recurringFriction: "Recurring friction" };
export default function FounderProfilePanel() {
  const [profile, setProfile] = useState<any>(null); const [selected, setSelected] = useState(""); const [value, setValue] = useState(""); const [notice, setNotice] = useState("");
  const load = async () => { const r = await fetch("/api/founder-profile", { cache: "no-store" }); if (r.ok) setProfile(await r.json()); };
  useEffect(() => { void load(); }, []);
  const edit = (key: string) => { setSelected(key); setValue(profile?.dimensions?.[key]?.value == null ? "" : JSON.stringify(profile.dimensions[key].value)); };
  const save = async () => { const parsed = (() => { try { return JSON.parse(value); } catch { return value; } })(); const r = await fetch("/api/founder-profile/update", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ dimension: selected, value: parsed, source: "Owner correction in Founder Profile Settings", confidence: "confirmed" }) }); setNotice(r.ok ? `${labels[selected]} confirmed and added to profile history.` : "Founder Profile update failed."); setSelected(""); await load(); };
  if (!profile) return <div className="mt-5 rounded-2xl border border-border bg-card p-5 text-sm text-muted-foreground">Loading Founder Profile…</div>;
  return <div className="mt-5 rounded-2xl border border-border bg-card p-5"><div className="flex items-start gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-primary/10 text-primary"><UserRound size={18} /></span><div><p className="lee-label text-primary">Founder Profile</p><h3 className="mt-1 text-lg font-semibold">How Lee understands your operating style</h3><p className="mt-1 text-xs text-muted-foreground">Only explicit or source-backed dimensions with high confidence are applied to context packets. Nothing is guessed.</p></div></div>{notice && <p className="mt-4 rounded-xl bg-primary/10 p-3 text-xs text-primary">{notice}</p>}<div className="mt-5 grid gap-3 md:grid-cols-2">{Object.entries(profile.dimensions ?? {}).map(([key, record]: [string, any]) => <div key={key} className="rounded-xl border border-border bg-muted/30 p-3.5"><div className="flex items-center justify-between gap-3"><p className="text-sm font-semibold">{labels[key] ?? key}</p><button onClick={() => edit(key)} className="rounded-lg p-1.5 text-muted-foreground hover:bg-muted hover:text-primary"><Pencil size={14} /></button></div><p className="mt-2 line-clamp-3 text-xs leading-relaxed text-muted-foreground">{record.value == null ? "Not learned yet" : typeof record.value === "string" ? record.value : JSON.stringify(record.value)}</p><div className="mt-3 flex items-center justify-between"><span className="lee-label text-muted-foreground">{record.confidence} confidence</span><span className="lee-label text-muted-foreground">{record.correctionCount} corrections</span></div></div>)}</div>{selected && <div className="mt-5 rounded-xl border border-primary/30 bg-primary/5 p-4"><p className="text-sm font-semibold">Confirm {labels[selected]}</p><textarea value={value} onChange={(e) => setValue(e.target.value)} className="mt-3 min-h-20 w-full rounded-xl border border-input bg-background px-3 py-2 text-sm" placeholder="Text, or valid JSON for lists/structured values" /><div className="mt-3 flex gap-2"><button onClick={() => void save()} className="rounded-lg bg-primary px-3 py-2 text-xs font-semibold text-primary-foreground"><CheckCircle2 className="mr-1 inline" size={13} />Confirm correction</button><button onClick={() => setSelected("")} className="rounded-lg border border-border px-3 py-2 text-xs">Cancel</button></div></div>}</div>;
}