import { useEffect, useState } from "react";
import { ArrowDown, GitBranch, RefreshCw } from "lucide-react";
export default function ImpactPage() {
  const [graph, setGraph] = useState<any>({ nodes: [], edges: [] }); const [selected, setSelected] = useState<any>(null); const [tree, setTree] = useState<any>(null);
  const load = async () => { const response = await fetch("/api/impact/graph", { cache: "no-store" }); if (response.ok) setGraph(await response.json()); };
  useEffect(() => { void load(); }, []);
  const choose = async (node: any) => { setSelected(node); const response = await fetch(`/api/impact/decision/${node.id}/tree`, { cache: "no-store" }); if (response.ok) setTree(await response.json()); };
  const renderTree = (items: any[], depth = 0): any => items.map((item) => <div key={item.edge.id} className="relative" style={{ marginLeft: depth * 22 }}><div className="flex items-center gap-2 rounded-lg bg-muted/40 p-2 text-xs"><ArrowDown size={13} className="text-primary" /><span className="font-semibold">{item.edge.edgeType}</span><span>{item.node?.label ?? "Unknown consequence"}</span><span className="ml-auto text-muted-foreground">{item.node?.observedAt ? new Date(item.node.observedAt).toLocaleDateString() : "observed"}</span></div>{renderTree(item.consequences ?? [], depth + 1)}</div>);
  return <div className="mx-auto max-w-[1250px]"><p className="lee-label text-primary">Operational archaeology</p><h1 className="mt-2 text-3xl font-semibold">Decision Impact Graph</h1><p className="mt-2 text-sm text-muted-foreground">Trace what decisions actually caused, enabled, prevented, accelerated, or delayed. User-declared edges are immediate; engine proposals remain reviewable.</p><div className="mt-5 grid gap-5 lg:grid-cols-[1fr_1.2fr]"><section className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center justify-between"><div><p className="lee-label text-primary">Impact nodes</p><h2 className="mt-1 text-xl font-semibold">{graph.nodes.length} tracked nodes</h2></div><button onClick={() => void load()} className="rounded-lg border border-border p-2"><RefreshCw size={14} /></button></div><div className="mt-4 space-y-2">{graph.nodes.length ? graph.nodes.map((node: any) => <button key={node.id} onClick={() => void choose(node)} className={`flex w-full items-center gap-3 rounded-xl border p-3 text-left ${selected?.id === node.id ? "border-primary bg-primary/10" : "border-border bg-muted/20"}`}><GitBranch size={16} className="text-primary" /><span className="flex-1"><span className="lee-label text-muted-foreground">{node.nodeType}</span><span className="mt-1 block text-sm font-semibold">{node.label}</span></span><span className="text-right"><span className="block text-lg font-semibold text-primary">{Number(node.impactScore).toFixed(1)}</span><span className="text-[10px] text-muted-foreground">impact</span></span></button>) : <p className="py-10 text-center text-sm text-muted-foreground">No causal nodes yet. Add a decision and consequence to begin.</p>}</div></section><section className="rounded-2xl border border-border bg-card p-5"><p className="lee-label text-primary">Impact chain</p><h2 className="mt-1 text-xl font-semibold">{selected ? selected.label : "Select a node"}</h2>{selected && <div className="mt-4 space-y-2">{tree?.consequences?.length ? renderTree(tree.consequences) : <p className="rounded-xl border border-dashed border-border p-8 text-center text-sm text-muted-foreground">No approved downstream consequences yet.</p>}</div>}{!selected && <div className="mt-8 rounded-xl border border-dashed border-border p-12 text-center text-sm text-muted-foreground">Choose a decision node to see its full consequence tree.</div>}</section></div></div>;
}