import { useEffect, useState } from "react";
import { Archive, BrainCircuit, Layers3 } from "lucide-react";
export default function MemoryHealthPanel() {
  const [status, setStatus] = useState<any>(null);
  const [error, setError] = useState('');
  useEffect(() => { fetch("/api/memory-architecture/status", { cache: "no-store" }).then((r) => { if (!r.ok) throw new Error(`Memory health unavailable (${r.status}).`); return r.json(); }).then((value) => { setStatus(value); setError(''); }).catch((cause) => setError(cause instanceof Error ? cause.message : 'Memory health unavailable.')); }, []);
  if (error) return <div className="mx-auto mt-5 max-w-[1280px] rounded-2xl border border-accent/30 bg-accent/10 p-5 text-sm text-accent-foreground">{error}</div>;
  if (!status) return <div className="mx-auto mt-5 max-w-[1280px] rounded-2xl border border-border bg-card p-5 text-sm text-muted-foreground">Loading memory health…</div>;
  return <div className="mx-auto mt-5 max-w-[1280px]"><div className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center gap-3"><BrainCircuit size={18} className="text-primary" /><div><p className="lee-label text-primary">Memory health</p><h3 className="mt-1 text-lg font-semibold">Tier distribution & compression</h3></div></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-muted/50 p-3"><p className="lee-label text-muted-foreground">Working memory</p><p className="mt-2 text-2xl font-semibold">{status.distribution?.working ?? 0}</p></div><div className="rounded-xl bg-muted/50 p-3"><p className="lee-label text-muted-foreground">Dormant</p><p className="mt-2 text-2xl font-semibold">{status.dormantCount}</p></div><div className="rounded-xl bg-muted/50 p-3"><p className="lee-label text-muted-foreground">Stage 2 coverage</p><p className="mt-2 text-2xl font-semibold">{Math.round(status.stage2Coverage * 100)}%</p></div></div><div className="mt-4 flex flex-wrap gap-2">{Object.entries(status.distribution ?? {}).map(([tier, count]) => <span key={tier} className="inline-flex items-center gap-1.5 rounded-full border border-border px-2.5 py-1 text-[11px] text-muted-foreground"><Layers3 size={12} />{tier} {String(count)}</span>)}</div><p className="mt-4 text-xs text-muted-foreground"><Archive className="mr-1 inline" size={13} />{status.consolidationBacklog} historical objects await Stage 2 consolidation.</p></div></div>;
}