import { useEffect, useState } from "react";
import { Check, Eye, Lightbulb, RefreshCw, X } from "lucide-react";
import WhyChainPanel from "./WhyChainPanel";
export default function ObservationsPage() {
  const [observations, setObservations] = useState<any[]>([]); const [opportunities, setOpportunities] = useState<any[]>([]); const [notice, setNotice] = useState("");
  const load = async () => { const [a, b] = await Promise.all([fetch("/api/curiosity/observations", { cache: "no-store" }), fetch("/api/curiosity/opportunities", { cache: "no-store" })]); if (a.ok) setObservations(await a.json()); if (b.ok) setOpportunities(await b.json()); };
  useEffect(() => { void load(); }, []);
  const transition = async (kind: string, id: string, lifecycle: string) => { const r = await fetch(`/api/curiosity/${kind}/${id}/${lifecycle}`, { method: "POST" }); setNotice(r.ok ? `${lifecycle.replace("_", " ")} recorded in the Event Log.` : "Lifecycle update failed."); await load(); };
  const scan = async () => { const r = await fetch("/api/curiosity/scan", { method: "POST" }); setNotice(r.ok ? "Curiosity and opportunity scans completed against internal evidence." : "Scan failed."); await load(); };
  const card = (item: any, kind: string) => <div key={item.id} className="rounded-xl border border-border bg-card p-4"><div className="flex items-start justify-between gap-3"><div><p className="lee-label text-primary">{(item.observationType ?? item.opportunityType).replaceAll("_", " ")}</p><h3 className="mt-2 text-sm font-semibold leading-relaxed">{item.headline}</h3></div><span className="lee-label text-muted-foreground">{item.confidence} · {item.lifecycle}</span></div><p className="mt-3 text-xs text-muted-foreground">{item.supportingEvidence.length} evidence links · relevance {Math.round(item.relevanceScore * 100)}%</p>{item.actionSuggestion && <p className="mt-3 rounded-lg bg-muted/50 p-3 text-xs text-muted-foreground">Suggested action: {item.actionSuggestion}</p>}<div className="mt-4 flex flex-wrap gap-2"><button onClick={() => void transition(kind, item.id, "acknowledged")} className="rounded-lg border border-border px-2.5 py-1.5 text-xs font-semibold"><Eye className="mr-1 inline" size={12} />Acknowledge</button><button onClick={() => void transition(kind, item.id, "acted_on")} className="rounded-lg border border-border px-2.5 py-1.5 text-xs font-semibold"><Check className="mr-1 inline" size={12} />Acted on</button><button onClick={() => void transition(kind, item.id, "dismissed")} className="rounded-lg border border-border px-2.5 py-1.5 text-xs font-semibold"><X className="mr-1 inline" size={12} />Dismiss</button></div></div>;
  return <div className="mx-auto max-w-[1280px]"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="lee-label text-primary">Proactive signal</p><h1 className="mt-2 text-3xl font-semibold">Observations & Opportunities</h1><p className="mt-2 text-sm text-muted-foreground">Evidence-backed internal signals. Lee notices; you decide.</p></div><div className="flex gap-2"><button onClick={() => void load()} className="rounded-xl border border-border bg-card px-3.5 py-2.5 text-xs font-semibold"><RefreshCw className="mr-2 inline" size={14} />Refresh</button><button onClick={() => void scan()} className="rounded-xl bg-primary px-3.5 py-2.5 text-xs font-semibold text-primary-foreground">Run scan</button></div></div>{notice && <div className="mt-4 rounded-xl border border-primary/25 bg-primary/10 px-4 py-3 text-sm text-primary">{notice}</div>}<div className="mt-5 grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center gap-2"><Eye size={16} className="text-primary" /><div><p className="lee-label text-primary">Curiosity Engine</p><h2 className="mt-1 text-xl font-semibold">{observations.length} observations</h2></div></div><div className="mt-4 space-y-3">{observations.length ? observations.map((item) => <div key={item.id}>{card(item, "observation")}<WhyChainPanel chain={item.whyChain} /></div>) : <p className="py-10 text-center text-sm text-muted-foreground">No observations yet. Run a scan when the evidence window has material.</p>}</div></section><section className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center gap-2"><Lightbulb size={16} className="text-primary" /><div><p className="lee-label text-primary">Opportunity Engine</p><h2 className="mt-1 text-xl font-semibold">{opportunities.length} opportunities</h2></div></div><div className="mt-4 space-y-3">{opportunities.length ? opportunities.map((item) => <div key={item.id}>{card(item, "opportunity")}<WhyChainPanel chain={item.whyChain} /></div>) : <p className="py-10 text-center text-sm text-muted-foreground">No opportunities yet. Connected graph evidence will appear here.</p>}</div></section></div></div>;
}