import { useEffect, useState } from "react";
import { Activity, Clock3, Layers3 } from "lucide-react";

export function OrchestrationPanel() {
  const [data, setData] = useState<any>({ queueDepth: {}, health: [], decisions: [] });
  const [error, setError] = useState('');
  useEffect(() => { fetch("/api/orchestration/status", { cache: "no-store" }).then((r) => { if (!r.ok) throw new Error(`Orchestration unavailable (${r.status}).`); return r.json(); }).then((v) => { setData(v); setError(''); }).catch((cause) => setError(cause instanceof Error ? cause.message : 'Orchestration unavailable.')); }, []);
  if (error) return <div className="mt-5 rounded-2xl border border-accent/30 bg-accent/10 p-5 text-sm text-accent-foreground">{error}</div>;
  return <div className="mt-5 grid gap-5 lg:grid-cols-[1fr_1fr]"><div className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center gap-2"><Activity size={16} className="text-primary" /><div><p className="lee-label text-primary">Orchestration</p><h3 className="mt-1 text-lg font-semibold">Work queue</h3></div></div><div className="mt-5 grid grid-cols-4 gap-2">{(["CRITICAL", "HIGH", "NORMAL", "LOW"] as const).map((level) => <div key={level} className="rounded-xl bg-muted/50 p-3 text-center"><p className="lee-label text-muted-foreground">{level}</p><p className="mt-2 text-xl font-semibold">{data.queueDepth?.[level] ?? 0}</p></div>)}</div><p className="mt-4 text-xs text-muted-foreground">Priority resolution is persisted and visible; critical work always wins.</p></div><div className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center gap-2"><Layers3 size={16} className="text-primary" /><div><p className="lee-label text-primary">Engine health</p><h3 className="mt-1 text-lg font-semibold">{data.health?.length ?? 0} registered engines</h3></div></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{(data.health ?? []).slice(0, 6).map((item: any) => <div key={item.engineName} className="flex items-center justify-between rounded-lg bg-muted/40 px-3 py-2 text-xs"><span>{item.engineName}</span><span className={item.errorCount ? "text-accent-foreground" : "text-primary"}>{item.errorCount ? `${item.errorCount} errors` : "nominal"}</span></div>)}</div></div></div>;
}