import { useEffect, useState } from "react";
import { CalendarCheck, Plus, RefreshCw, Target } from "lucide-react";
export default function StrategyPage() {
  const [data, setData] = useState<any>({ objectives: [], reviews: [] }); const [question, setQuestion] = useState(""); const [notice, setNotice] = useState("");
  const load = async () => { const r = await fetch("/api/strategy", { cache: "no-store" }); if (r.ok) setData(await r.json()); };
  useEffect(() => { void load(); }, []);
  const review = async () => { const r = await fetch("/api/strategy/review", { method: "POST" }); setNotice(r.ok ? "Strategy review recorded." : "Strategy review failed."); await load(); };
  const add = async () => { if (!question.trim()) return; const r = await fetch("/api/strategy/objectives", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ objective: question, horizon: "quarter" }) }); setNotice(r.ok ? "Objective declared and added to strategy." : "Objective could not be saved."); setQuestion(""); await load(); };
  return <div className="mx-auto max-w-[1280px]"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="lee-label text-primary">Long horizon</p><h1 className="mt-2 text-3xl font-semibold">Strategy</h1><p className="mt-2 text-sm text-muted-foreground">Objectives are declared by you, reviewed with Lee, and carried into context.</p></div><button onClick={() => void review()} className="rounded-xl bg-primary px-3.5 py-2.5 text-xs font-semibold text-primary-foreground"><CalendarCheck className="mr-2 inline" size={14} />Run strategy review</button></div>{notice && <p className="mt-4 rounded-xl border border-primary/25 bg-primary/10 px-4 py-3 text-sm text-primary">{notice}</p>}<div className="mt-5 flex gap-2"><input value={question} onChange={(e) => setQuestion(e.target.value)} onKeyDown={(e) => e.key === "Enter" && void add()} placeholder="Declare a strategic objective…" className="h-11 flex-1 rounded-xl border border-input bg-card px-4 text-sm outline-none focus:border-primary" /><button onClick={() => void add()} className="rounded-xl border border-border px-3.5 text-xs font-semibold"><Plus className="mr-1 inline" size={14} />Declare</button></div><div className="mt-5 grid gap-4 md:grid-cols-2">{data.objectives.map((item: any) => <div key={item.id} className="rounded-2xl border border-border bg-card p-5"><div className="flex items-start justify-between gap-3"><div className="flex gap-3"><Target className="mt-1 text-primary" size={18} /><div><p className="lee-label text-primary">{item.horizon} · {item.status}</p><h2 className="mt-1 text-lg font-semibold">{item.objective}</h2></div></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-muted/50 p-3"><p className="lee-label text-muted-foreground">Blockers</p><p className="mt-2 text-sm">{item.blockers.length ? item.blockers.join(", ") : "None recorded"}</p></div><div className="rounded-xl bg-muted/50 p-3"><p className="lee-label text-muted-foreground">Next action</p><p className="mt-2 text-sm">{item.nextAction ?? "Review with Lee"}</p></div></div></div>)}{!data.objectives.length && <div className="rounded-2xl border border-dashed border-border p-10 text-center text-sm text-muted-foreground">No strategic objectives declared yet.</div>}</div></div>;
}