import { useEffect, useState } from "react";
import { ChevronDown, ShieldCheck } from "lucide-react";
const tone = (score: number) => score >= 80 ? "text-primary" : score >= 60 ? "text-accent-foreground" : "text-destructive";
export default function TrustScorePanel() {
  const [data, setData] = useState<any>(null); const [expanded, setExpanded] = useState<string | null>(null); const [history, setHistory] = useState<any[]>([]);
  const load = async () => { const r = await fetch("/api/health/trust", { cache: "no-store" }); if (r.ok) setData(await r.json()); };
  useEffect(() => { void load(); }, []);
  const open = async (name: string) => { if (expanded === name) { setExpanded(null); return; } const r = await fetch(`/api/health/trust/${encodeURIComponent(name)}`); if (r.ok) setHistory(await r.json()); setExpanded(name); };
  if (!data) return null;
  return <div className="mx-auto mt-5 max-w-[1280px]"><div className="rounded-2xl border border-border bg-card p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><ShieldCheck size={19} className="text-primary" /><div><p className="lee-label text-primary">Trust system</p><h3 className="mt-1 text-lg font-semibold">Earned reliability by subsystem</h3></div></div><span className={`text-2xl font-semibold ${tone(data.average)}`}>{data.average}<span className="text-sm text-muted-foreground"> / 100 average</span></span></div><p className="mt-3 text-xs text-muted-foreground">Trust is separate from information confidence. It changes only from recorded outcomes, corrections, failures, and recovery.</p><div className="mt-5 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{data.scores.map((item: any) => <div key={item.subsystemName} className="rounded-xl border border-border bg-muted/30 p-3"><button onClick={() => void open(item.subsystemName)} className="flex w-full items-center justify-between gap-2 text-left"><span className="min-w-0 truncate text-xs font-semibold">{item.subsystemName}</span><span className={`flex items-center gap-1 text-sm font-semibold ${tone(item.score)}`}>{Math.round(item.score)}<ChevronDown size={13} className={expanded === item.subsystemName ? "rotate-180" : ""} /></span></button><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-secondary"><div className={`h-full rounded-full ${item.score >= 80 ? "bg-primary" : item.score >= 60 ? "bg-accent" : "bg-destructive"}`} style={{ width: `${item.score}%` }} /></div>{expanded === item.subsystemName && <div className="mt-3 border-t border-border pt-2 text-[11px] text-muted-foreground">{history.length ? history.slice(0, 5).map((event: any) => <p key={event.id} className="py-1">{event.eventType} {event.delta > 0 ? "+" : ""}{event.delta} · {event.reason}</p>) : "No trust events yet."}</div>}</div>)}</div></div></div>;
}