import React, { useEffect, useState } from 'react';
import { Feather } from '@expo/vector-icons';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { Screen, Card, Eyebrow, SectionLabel, Title } from '@/components/Screen';
import { useColors } from '@/hooks/useColors';
import { useLee } from '@/context/LeeContext';
import type { Alert } from '@/lib/types';

export default function AlertsTab() {
  const colors = useColors(); const { api } = useLee(); const [alerts, setAlerts] = useState<Alert[]>([]); const [error, setError] = useState('');
  const { id } = useLocalSearchParams<{ id?: string }>();
  async function load() { if (api) try { setError(''); setAlerts(await api.alerts()); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Alerts are unavailable.'); } }
  useEffect(() => { void load(); }, [api]);
  async function dismiss(id: string) { if (!api) return; await api.alertAction(id, 'dismiss'); setAlerts((current) => current.filter((alert) => alert.id !== id)); }
  return <Screen refreshing={false}><Eyebrow>Signal above digest</Eyebrow><Title subtitle="Only items that need a change in attention show up here.">Alerts.</Title>{error ? <Text style={[styles.body, { color: colors.destructive }]}>{error}</Text> : null}<SectionLabel>{alerts.length} active signals</SectionLabel>{alerts.length ? alerts.map((alert) => <Card key={alert.id} style={{ borderColor: alert.id === id ? colors.primary : alert.severity === 'critical' ? colors.destructive : colors.border }}><View style={styles.row}><View style={[styles.icon, { backgroundColor: alert.severity === 'critical' ? colors.destructive : colors.accent }]}><Feather name={alert.severity === 'critical' ? 'alert-octagon' : 'alert-triangle'} size={18} color={alert.severity === 'critical' ? colors.destructiveForeground : colors.primary} /></View><View style={styles.copy}><Text style={[styles.title, { color: colors.foreground }]}>{alert.title}</Text><Text style={[styles.meta, { color: colors.mutedForeground }]}>{alert.project ?? 'Lee' } · {alert.severity}</Text></View></View><Text style={[styles.body, { color: colors.mutedForeground }]}>{alert.reason ?? alert.body ?? 'This signal needs review.'}</Text><View style={styles.actions}><Pressable onPress={() => void dismiss(alert.id)}><Text style={[styles.action, { color: colors.mutedForeground }]}>Dismiss</Text></Pressable><Pressable onPress={() => router.push({ pathname: '/(tabs)/ask', params: { prompt: `Review this alert: ${alert.title}. ${alert.reason ?? alert.body ?? ''}` } })}><Text style={[styles.action, { color: colors.primary }]}>Open in Ask Lee</Text></Pressable></View></Card>) : <Card><Text style={[styles.body, { color: colors.mutedForeground }]}>{error ? 'Cached alerts are unavailable.' : 'No alerts are currently above the digest level.'}</Text></Card>}</Screen>;
}
const styles = StyleSheet.create({ row: { flexDirection: 'row', gap: 12, alignItems: 'center' }, icon: { width: 40, height: 40, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, copy: { flex: 1 }, title: { fontSize: 15, fontFamily: 'Inter_700Bold' }, meta: { fontSize: 11, fontFamily: 'Inter_400Regular', marginTop: 3 }, body: { fontSize: 14, lineHeight: 21, fontFamily: 'Inter_400Regular' }, actions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 20 }, action: { fontSize: 12, fontFamily: 'Inter_700Bold' } });