import React, { useEffect, useState } from 'react';
import { Feather } from '@expo/vector-icons';
import { Alert as NativeAlert, Pressable, StyleSheet, Text, View } from 'react-native';
import { Screen, Card, Eyebrow, SectionLabel, Title } from '@/components/Screen';
import { useColors } from '@/hooks/useColors';
import { useLee } from '@/context/LeeContext';
import type { Approval } from '@/lib/types';

export default function ApprovalsTab() {
  const colors = useColors(); const { api } = useLee(); const [approvals, setApprovals] = useState<Approval[]>([]); const [error, setError] = useState('');
  async function load() { if (api) try { setError(''); setApprovals(await api.approvals()); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Approvals are unavailable.'); } }
  useEffect(() => { void load(); }, [api]);
  function decide(approval: Approval, decision: 'approve' | 'hold' | 'reject') { NativeAlert.alert(`${decision[0].toUpperCase()}${decision.slice(1)} this action?`, 'This human decision is recorded by Lee.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Confirm', style: decision === 'reject' ? 'destructive' : 'default', onPress: async () => { if (!api) return; await api.approve(approval.id, decision); setApprovals((current) => decision === 'hold' ? current : current.filter((item) => item.id !== approval.id)); } }]); }
  return <Screen><Eyebrow>Governance queue</Eyebrow><Title subtitle="Lee can prepare the decision. You keep the final say.">Approvals.</Title>{error ? <Text style={[styles.body, { color: colors.destructive }]}>{error}</Text> : null}<SectionLabel>{approvals.length} pending decisions</SectionLabel>{approvals.length ? approvals.map((approval) => <Card key={approval.id}><View style={styles.row}><Feather name="shield" size={18} color={colors.destructive} /><View style={styles.copy}><Text style={[styles.title, { color: colors.foreground }]}>{approval.action ?? approval.actionClass ?? 'Governed action'}</Text><Text style={[styles.meta, { color: colors.mutedForeground }]}>{approval.risk ?? 'review'} risk · {approval.targetSystem ?? 'Lee'}</Text></View></View><Text style={[styles.body, { color: colors.mutedForeground }]}>{approval.reason ?? approval.reasonCodes?.join(', ') ?? 'Human review is required.'}</Text><View style={[styles.verdict, { backgroundColor: colors.secondary }]}><Text style={[styles.verdictText, { color: colors.foreground }]}>{approval.verdict ?? 'Review the action and its evidence before deciding.'}</Text></View><View style={styles.actions}><Pressable onPress={() => decide(approval, 'hold')}><Text style={[styles.action, { color: colors.mutedForeground }]}>Hold</Text></Pressable><Pressable onPress={() => decide(approval, 'reject')}><Text style={[styles.action, { color: colors.destructive }]}>Reject</Text></Pressable><Pressable onPress={() => decide(approval, 'approve')}><Text style={[styles.action, { color: colors.primary }]}>Approve</Text></Pressable></View></Card>) : <Card><Text style={[styles.body, { color: colors.mutedForeground }]}>{error ? 'Cached approvals are unavailable.' : 'No governed action is waiting for your decision.'}</Text></Card>}</Screen>;
}
const styles = StyleSheet.create({ row: { flexDirection: 'row', gap: 12, alignItems: 'flex-start' }, copy: { flex: 1 }, title: { fontSize: 15, fontFamily: 'Inter_700Bold' }, meta: { fontSize: 11, marginTop: 4, fontFamily: 'Inter_400Regular' }, body: { fontSize: 14, lineHeight: 21, fontFamily: 'Inter_400Regular' }, verdict: { borderRadius: 10, padding: 11 }, verdictText: { fontSize: 12, lineHeight: 18, fontFamily: 'Inter_500Medium' }, actions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 20 }, action: { fontSize: 12, fontFamily: 'Inter_700Bold' } });