import React, { useRef, useState } from 'react';
import { Feather } from '@expo/vector-icons';
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { KeyboardAvoidingView } from 'react-native-keyboard-controller';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Screen, Card, Eyebrow, Title } from '@/components/Screen';
import { useColors } from '@/hooks/useColors';
import { useLee } from '@/context/LeeContext';

type Message = { id: string; role: 'user' | 'assistant'; content: string; model?: string; cost?: number; status?: 'streaming' | 'complete' | 'error' | 'cancelled'; evidence?: number; question?: string };
let counter = 0;
const id = () => `m-${Date.now()}-${++counter}`;

export default function AskTab() {
  const colors = useColors(); const { api } = useLee(); const insets = useSafeAreaInsets(); const input = useRef<TextInput>(null);
  const [question, setQuestion] = useState(''); const [messages, setMessages] = useState<Message[]>([]); const [loading, setLoading] = useState(false); const abort = useRef<AbortController | null>(null);
  async function ask(retryText?: string) { const text = (retryText ?? question).trim(); if (!text || !api || loading) return; setQuestion(''); const assistantId = id(); setMessages((current) => [...current, { id: id(), role: 'user', content: text }, { id: assistantId, role: 'assistant', content: '', status: 'streaming', question: text }]); setLoading(true); abort.current = new AbortController(); try { await api.askStream(text, (event) => setMessages((current) => current.map((item) => item.id !== assistantId ? item : event.type === 'chunk' ? { ...item, content: item.content + event.data.text } : event.type === 'start' ? { ...item, model: event.data.model, evidence: event.data.evidence.length } : event.type === 'complete' ? { ...item, content: event.data.answer, model: event.data.model, cost: event.data.estimatedCostUsd, evidence: event.data.evidence.length, status: 'complete' } : { ...item, content: event.data.error, status: 'error' })), abort.current.signal); } catch (error) { const cancelled = abort.current?.signal.aborted; setMessages((current) => current.map((item) => item.id === assistantId ? { ...item, content: cancelled ? 'Response cancelled. You can try again.' : error instanceof Error ? error.message : 'Lee could not answer while offline.', status: cancelled ? 'cancelled' : 'error' } : item)); } finally { abort.current = null; setLoading(false); input.current?.focus(); } }
  function cancel() { abort.current?.abort(); }
  return <KeyboardAvoidingView behavior="padding" style={{ flex: 1 }}><Screen><Eyebrow>Low-cost mode · evidence first</Eyebrow><Title subtitle="A fast question is often enough to unblock the next move.">Ask Lee.</Title><FlatList data={[...messages].reverse()} inverted={messages.length > 0} scrollEnabled={!!messages.length} keyboardShouldPersistTaps="handled" keyExtractor={(item) => item.id} contentContainerStyle={{ gap: 10 }} renderItem={({ item }) => <View style={[styles.bubble, { alignSelf: item.role === 'user' ? 'flex-end' : 'flex-start', backgroundColor: item.role === 'user' ? colors.accent : colors.card, borderColor: item.role === 'user' ? colors.accent : colors.border }]}><Text style={[styles.message, { color: colors.foreground }]}>{item.content || (item.status === 'streaming' ? '…' : '')}</Text>{item.role === 'assistant' && <><Text style={[styles.meta, { color: colors.mutedForeground }]}>{item.status === 'streaming' ? 'Lee is responding…' : `${item.model ?? 'Lee'} · ${item.cost == null ? '—' : `$${item.cost.toFixed(4)}`} estimated${item.evidence == null ? '' : ` · ${item.evidence} evidence`}`}</Text>{item.status === 'error' && <Pressable onPress={() => void ask(item.question)}><Text style={[styles.retry, { color: colors.primary }]}>Try again</Text></Pressable>}</>}</View>} ListHeaderComponent={loading ? <Pressable onPress={cancel} style={[styles.typing, { backgroundColor: colors.card }]}><ActivityIndicator size="small" color={colors.primary} /><Text style={[styles.meta, { color: colors.mutedForeground }]}>Lee is responding… Tap to cancel</Text></Pressable> : null} /><View style={[styles.composer, { backgroundColor: colors.card, borderColor: colors.border, paddingBottom: Math.max(insets.bottom, 10) }]}><TextInput ref={input} testID="ask-input" value={question} onChangeText={setQuestion} multiline blurOnSubmit={false} placeholder="What do you need to understand?" placeholderTextColor={colors.mutedForeground} style={[styles.input, { color: colors.foreground }]} /><Pressable testID="ask-button" onPress={() => loading ? cancel() : void ask()} style={[styles.send, { backgroundColor: colors.primary }]}><Feather name={loading ? 'x' : 'arrow-up'} size={18} color={colors.primaryForeground} /></Pressable></View></Screen></KeyboardAvoidingView>;
}
const styles = StyleSheet.create({ bubble: { maxWidth: '88%', borderWidth: 1, borderRadius: 16, padding: 13 }, message: { fontSize: 15, lineHeight: 22, fontFamily: 'Inter_400Regular' }, meta: { fontSize: 10, marginTop: 7, fontFamily: 'Inter_500Medium' }, retry: { fontSize: 12, marginTop: 8, fontFamily: 'Inter_500Medium' }, typing: { flexDirection: 'row', gap: 8, alignItems: 'center', padding: 12, borderRadius: 14 }, composer: { flexDirection: 'row', alignItems: 'flex-end', gap: 8, borderWidth: 1, borderRadius: 16, padding: 8 }, input: { flex: 1, minHeight: 42, maxHeight: 110, fontSize: 15, lineHeight: 21, fontFamily: 'Inter_400Regular', paddingHorizontal: 8 }, send: { width: 40, height: 40, borderRadius: 13, alignItems: 'center', justifyContent: 'center' } });