import React, { useEffect, useState } from 'react';
import { Feather } from '@expo/vector-icons';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Screen, Card, Eyebrow, SectionLabel, Title } from '@/components/Screen';
import { useColors } from '@/hooks/useColors';
import { useLee } from '@/context/LeeContext';
import { getWaitingCache, saveWaitingCache } from '@/lib/storage';
import type { WaitingLoop } from '@/lib/types';

export default function WaitingTab() {
  const colors = useColors();
  const { api } = useLee();
  const [loops, setLoops] = useState<WaitingLoop[]>([]);
  const [offline, setOffline] = useState(false);
  useEffect(() => { void (async () => { setLoops(await getWaitingCache()); if (api) try { const live = await api.waiting(); setLoops(live); await saveWaitingCache(live); setOffline(false); } catch { setOffline(true); } })(); }, [api]);
  async function action(id: string, next: 'resolve' | 'snooze') { if (!api) return; await api.waitingAction(id, next); setLoops((current) => next === 'resolve' ? current.filter((loop) => loop.id !== id) : current); }
  return <Screen refreshing={false}><View style={styles.header}><View><Eyebrow>{offline ? 'Cached · offline' : 'Open loops'}</Eyebrow><Title subtitle="Small unresolved things become expensive when they stay invisible.">Waiting on.</Title></View><View style={[styles.count, { backgroundColor: colors.accent }]}><Text style={[styles.countText, { color: colors.primary }]}>{loops.length}</Text></View></View><Card style={{ backgroundColor: colors.accent, borderColor: colors.accent }}><Text style={[styles.summary, { color: colors.accentForeground }]}>{loops.length} open loop{loops.length === 1 ? '' : 's'}</Text><Text style={[styles.body, { color: colors.accentForeground }]}>LEE ranks waiting from importance, elapsed time, cadence, deadlines, project impact, and evidence. It never sends a follow-up automatically.</Text></Card><SectionLabel>By urgency</SectionLabel>{loops.length ? loops.map((loop) => { const score = Number(loop.waitingScore ?? loop.metadata?.waitingScore ?? 0); const risk = score >= 75 ? 'high' : score >= 48 ? 'medium' : 'low'; return <Card key={loop.id}><View style={styles.row}><View style={[styles.risk, { backgroundColor: risk === 'high' ? colors.destructive : risk === 'medium' ? colors.secondary : colors.accent }]}><Text style={[styles.riskText, { color: risk === 'high' ? colors.destructiveForeground : colors.foreground }]}>{risk.toUpperCase()}</Text></View><Text style={[styles.days, { color: colors.mutedForeground }]}>{Math.max(0, Math.floor((Date.now() - new Date(loop.waitingSince).getTime()) / 86400000))}d · {score || '—'}</Text></View><Text style={[styles.title, { color: colors.foreground }]}>{loop.subject}</Text><Text style={[styles.meta, { color: colors.mutedForeground }]}>{loop.direction ? loop.direction.replaceAll('_', ' ') : loop.owner ?? 'Unassigned'} · {loop.nextCheckAt ? `next check ${new Date(loop.nextCheckAt).toLocaleDateString()}` : 'no check scheduled'}</Text><Text style={[styles.body, { color: colors.mutedForeground }]}>{String(loop.metadata?.recommendedAction ?? 'Review the source and choose the next human action.')}</Text><View style={styles.actions}><Pressable onPress={() => void action(loop.id, 'snooze')} style={[styles.smallButton, { borderColor: colors.border }]}><Text style={[styles.buttonLabel, { color: colors.foreground }]}>Snooze</Text></Pressable><Pressable onPress={() => void action(loop.id, 'resolve')} style={[styles.smallButton, { backgroundColor: colors.primary }]}><Text style={[styles.buttonLabel, { color: colors.primaryForeground }]}>Resolve loop</Text></Pressable></View></Card>; }) : <Card><Text style={[styles.body, { color: colors.mutedForeground }]}>Nothing is currently waiting on a person or system.</Text></Card>}</Screen>;
}
const styles = StyleSheet.create({ header: { flexDirection: 'row', justifyContent: 'space-between' }, count: { width: 44, height: 44, borderRadius: 15, alignItems: 'center', justifyContent: 'center' }, countText: { fontSize: 20, fontFamily: 'Inter_700Bold' }, summary: { fontSize: 22, fontFamily: 'Inter_700Bold' }, body: { fontSize: 14, lineHeight: 21, fontFamily: 'Inter_400Regular' }, row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, risk: { borderRadius: 6, paddingHorizontal: 7, paddingVertical: 4 }, riskText: { fontSize: 9, letterSpacing: 0.8, fontFamily: 'Inter_700Bold' }, days: { fontSize: 13, fontFamily: 'Inter_600SemiBold' }, title: { fontSize: 16, fontFamily: 'Inter_700Bold' }, meta: { fontSize: 12, fontFamily: 'Inter_400Regular' }, actions: { flexDirection: 'row', gap: 8, marginTop: 4 }, smallButton: { borderWidth: 1, borderRadius: 9, paddingVertical: 8, paddingHorizontal: 13 }, buttonLabel: { fontSize: 12, fontFamily: 'Inter_600SemiBold' } });