import { and, desc, eq, gte, isNull, sql } from "drizzle-orm";
import { statfsSync } from "node:fs";
import { costRecord, db, eventLog, resourceAlert, resourceQuota, resourceSnapshot } from "@workspace/db";
import { checkPolicy } from "./policy";
export type ResourceLevel = "HEALTHY" | "CONSTRAINED" | "CRITICAL";
const worst = (levels: ResourceLevel[]) => levels.includes("CRITICAL") ? "CRITICAL" : levels.includes("CONSTRAINED") ? "CONSTRAINED" : "HEALTHY" as ResourceLevel;
const levelFor = (value: number, constrained: number, critical: number): ResourceLevel => value >= critical ? "CRITICAL" : value >= constrained ? "CONSTRAINED" : "HEALTHY";
export async function sampleResources(input: { batteryLevel?: number; charging?: boolean } = {}) {
  const memory = process.memoryUsage(); const memoryPercent = memory.heapTotal ? (memory.heapUsed / memory.heapTotal) * 100 : 0; const cpuPercent = 0;
  const disk = statfsSync(process.cwd()); const diskAvailableGb = (Number(disk.bavail) * Number(disk.bsize)) / 1024 ** 3; const diskPercent = 100 - Math.min(100, diskAvailableGb / 100 * 100);
  const dayStart = new Date(); dayStart.setHours(0, 0, 0, 0); const [cost] = await db.select({ total: sql<number>`coalesce(sum(${costRecord.estimatedCostUsd}), 0)` }).from(costRecord).where(gte(costRecord.recordedAt, dayStart));
  const policy = await checkPolicy("resource", "sample", {}, "Resource Engine"); const thresholds = policy.value as any;
  const dimensions = { cpu: { level: levelFor(cpuPercent, thresholds.cpuConstrainedPercent, thresholds.cpuCriticalPercent), value: cpuPercent, unit: "percent", trend: "stable" }, memory: { level: levelFor(memoryPercent, thresholds.memoryConstrainedPercent, thresholds.memoryCriticalPercent), value: memoryPercent, unit: "percent", trend: "stable" }, disk: { level: levelFor(diskPercent, thresholds.diskConstrainedPercent, thresholds.diskCriticalPercent), value: diskPercent, availableGb: Number(diskAvailableGb.toFixed(2)), unit: "percent", trend: "stable" }, token_budget: { level: "HEALTHY" as ResourceLevel, usedToday: 0, burnRatePerHour: 0, trend: "stable" }, cost_budget: { level: "HEALTHY" as ResourceLevel, usedTodayUsd: Number(cost?.total ?? 0), trend: "stable" }, api_quotas: { level: "HEALTHY" as ResourceLevel, providers: [], trend: "stable" }, network: { level: "HEALTHY" as ResourceLevel, connection: "high", latencyMs: null, trend: "stable" }, battery: { level: input.batteryLevel === undefined ? "HEALTHY" as ResourceLevel : levelFor(100 - input.batteryLevel, 100 - thresholds.batteryConstrainedPercent, 100 - thresholds.batteryCriticalPercent), levelPercent: input.batteryLevel ?? null, charging: input.charging ?? null, trend: "stable" } };
  const overallState = worst(Object.values(dimensions).map((dimension) => dimension.level)); const [snapshot] = await db.insert(resourceSnapshot).values({ dimensionStates: dimensions, overallState }).returning();
  await db.insert(eventLog).values({ eventType: "ResourceStateSampled", aggregateType: "resource_snapshot", aggregateId: snapshot.id, sourceRef: "resource-engine", occurredAt: new Date(), payload: { overallState, dimensions } });
  if (overallState !== "HEALTHY") await db.insert(resourceAlert).values({ dimension: Object.entries(dimensions).find(([, value]) => value.level === overallState)?.[0] ?? "system", level: overallState, title: `Resource state ${overallState.toLowerCase()}`, details: dimensions });
  return { overallState, dimensions, sampledAt: snapshot.sampledAt, snapshotId: snapshot.id };
}
export async function getResourceState() { const [latest] = await db.select().from(resourceSnapshot).orderBy(desc(resourceSnapshot.sampledAt)).limit(1); return latest ? { overallState: latest.overallState, dimensions: latest.dimensionStates, sampledAt: latest.sampledAt, snapshotId: latest.id } : sampleResources(); }
export async function updateQuota(provider: string, used: number, limit: number, resetAt?: Date) { const [row] = await db.insert(resourceQuota).values({ provider, used, limit, resetAt, updatedAt: new Date() }).onConflictDoUpdate({ target: resourceQuota.provider, set: { used, limit, resetAt, updatedAt: new Date() } }).returning(); return row; }
export async function resourceStatus() { const state = await getResourceState(); const alerts = await db.select().from(resourceAlert).where(isNull(resourceAlert.resolvedAt)).orderBy(desc(resourceAlert.createdAt)).limit(50); const quotas = await db.select().from(resourceQuota).orderBy(resourceQuota.provider); return { state, alerts, quotas }; }