import { Router, type IRouter } from "express";
import healthRouter from "./health";
import understandingRouter from "./understanding";
import reasoningRouter from "./reasoning";
import connectorsRouter from "./connectors";
import costsRouter from "./costs";
import brainVersionsRouter from "./brain-versions";
import schedulerRouter from "./scheduler";
import governanceRouter from "./governance";
import memoryRouter from "./memory";
import graphRouter from "./graph";
import relationshipsRouter from "./relationships";
import reviewsRouter from "./reviews";
import institutionalKnowledgeRouter from "./institutional-knowledge";
import selfImprovementRouter from "./self-improvement";
import systemEconomicsRouter from "./system-economics";
import identityRouter from "./identity";
import executiveObjectivesRouter from "./executive-objectives";
import organizationalMemoryRouter from "./organizational-memory";
import decisionMemoryRouter from "./decision-memory";
import foundationRouter from "./foundation";
import authRouter from "./auth";
import importsRouter from "./imports";
import timeRouter from "./time";
import aiRouter from "./ai";
import androidRouter from "./android";
import backupsRouter from "./backups";
import orchestrationRouter from "./orchestration";
import founderProfileRouter from "./founder-profile";
import memoryArchitectureRouter from "./memory-architecture";
import curiosityRouter from "./curiosity";
import trustRouter from "./trust";
import strategyRouter from "./strategy";
import learningRouter from "./learning";
import workspaceRouter from "./workspace";
import constitutionRouter from "./constitution";
import confidenceRouter from "./confidence";
import ledgersRouter from "./ledgers";
import whyProvenanceRouter from "./why-provenance";
import assumptionsRouter from "./assumptions";
import impactRouter from "./impact";
import timelineRouter from "./timeline";
import queryRouter from "./query";
import explanationsRouter from "./explanations";
import semanticRouter from "./semantic";
import policyRouter from "./policy";
import resourcesRouter from "./resources";
import intentsRouter from "./intents";
import stateRouter from "./state";
import selfTestRouter from "./self-test";
import recoveryRouter from "./recovery";
import ownershipRouter from "./ownership";
import agingRouter from "./aging";
import manifestRouter from "./manifest";
import worldStateRouter from "./world-state";
import operationalMemoryRouter from "./operational-memory";
import initiativeRouter from "./initiative";
import operationalIntelligenceRouter from "./operational-intelligence";
import providersRouter from "./providers";
import bootstrapRouter from "./bootstrap";
import executiveLoopRouter from "./executive-loop";
import systemContractRouter from "./system-contract";
import operationalConfidenceRouter from "./operational-confidence";
import projectMomentumRouter from "./project-momentum";
import opportunityRouter from "./opportunity";
import operationalCapacityRouter from "./operational-capacity";
import strategicAnchorsRouter from "./strategic-anchors";
import portfolioIntelligenceRouter from "./portfolio-intelligence";
import timeMachineRouter from "./time-machine";
import uncertaintyRouter from "./uncertainty";
import resourceAllocationRouter from "./resource-allocation";
import executionReadinessRouter from "./execution-readiness";
import portfolioDependencyRouter from "./portfolio-dependency";
import androidPairingRouter from "./android-pairing";
import universalSystemsRouter from "./universal-systems";
import connectionCenterRouter from "./connection-center";
import storageRouter from "./storage";
import emailRouter from "./email";
import desktopSetupRouter from "./desktop-setup";

const router: IRouter = Router();

router.use(healthRouter);
router.use(understandingRouter);
router.use(reasoningRouter);
router.use(connectorsRouter);
router.use(costsRouter);
router.use(brainVersionsRouter);
router.use(schedulerRouter);
router.use(governanceRouter);
router.use(memoryRouter);
router.use(graphRouter);
router.use(relationshipsRouter);
router.use(reviewsRouter);
router.use(institutionalKnowledgeRouter);
router.use(selfImprovementRouter);
router.use(systemEconomicsRouter);
router.use(identityRouter);
router.use(executiveObjectivesRouter);
router.use(organizationalMemoryRouter);
router.use(decisionMemoryRouter);
router.use(authRouter);
router.use(importsRouter);
router.use(timeRouter);
router.use(aiRouter);
router.use(androidRouter);
router.use(backupsRouter);
router.use(orchestrationRouter);
router.use(founderProfileRouter);
router.use(memoryArchitectureRouter);
router.use(curiosityRouter);
router.use(trustRouter);
router.use(strategyRouter);
router.use(learningRouter);
router.use(workspaceRouter);
router.use(constitutionRouter);
router.use(confidenceRouter);
router.use(ledgersRouter);
router.use(whyProvenanceRouter);
router.use(assumptionsRouter);
router.use(impactRouter);
router.use(timelineRouter);
router.use(queryRouter);
router.use(explanationsRouter);
router.use(semanticRouter);
router.use(policyRouter);
router.use(resourcesRouter);
router.use(intentsRouter);
router.use(stateRouter);
router.use(manifestRouter);
router.use(worldStateRouter);
router.use(operationalMemoryRouter);
router.use(initiativeRouter);
router.use(operationalIntelligenceRouter);
router.use(providersRouter);
router.use(bootstrapRouter);
router.use(executiveLoopRouter);
router.use(systemContractRouter);
router.use(operationalConfidenceRouter);
router.use(projectMomentumRouter);
router.use(opportunityRouter);
router.use(operationalCapacityRouter);
router.use(strategicAnchorsRouter);
router.use(portfolioIntelligenceRouter);
router.use(timeMachineRouter);
router.use(uncertaintyRouter);
router.use(resourceAllocationRouter);
router.use(executionReadinessRouter);
router.use(portfolioDependencyRouter);
router.use(androidPairingRouter);
  router.use(universalSystemsRouter);
  router.use(connectionCenterRouter);
  router.use(storageRouter);
router.use(emailRouter);
router.use(desktopSetupRouter);
router.use(selfTestRouter);
router.use(recoveryRouter);
router.use(ownershipRouter);
router.use(agingRouter);
router.use(foundationRouter);

export default router;
