import { Router, type IRouter } from "express";
import healthRouter from "./health";
import understandingRouter from "./understanding";
import reasoningRouter from "./reasoning";
import connectorsRouter from "./connectors";
import costsRouter from "./costs";
import brainVersionsRouter from "./brain-versions";
import schedulerRouter from "./scheduler";
import governanceRouter from "./governance";
import memoryRouter from "./memory";
import graphRouter from "./graph";
import relationshipsRouter from "./relationships";
import reviewsRouter from "./reviews";
import institutionalKnowledgeRouter from "./institutional-knowledge";
import selfImprovementRouter from "./self-improvement";
import systemEconomicsRouter from "./system-economics";
import identityRouter from "./identity";
import executiveObjectivesRouter from "./executive-objectives";
import organizationalMemoryRouter from "./organizational-memory";
import decisionMemoryRouter from "./decision-memory";
import foundationRouter from "./foundation";
import authRouter from "./auth";
import importsRouter from "./imports";
import timeRouter from "./time";
import aiRouter from "./ai";
import androidRouter from "./android";
import backupsRouter from "./backups";
import orchestrationRouter from "./orchestration";
import founderProfileRouter from "./founder-profile";
import memoryArchitectureRouter from "./memory-architecture";
import curiosityRouter from "./curiosity";
import trustRouter from "./trust";
import strategyRouter from "./strategy";
import learningRouter from "./learning";
import workspaceRouter from "./workspace";
import constitutionRouter from "./constitution";
import confidenceRouter from "./confidence";

const router: IRouter = Router();

router.use(healthRouter);
router.use(understandingRouter);
router.use(reasoningRouter);
router.use(connectorsRouter);
router.use(costsRouter);
router.use(brainVersionsRouter);
router.use(schedulerRouter);
router.use(governanceRouter);
router.use(memoryRouter);
router.use(graphRouter);
router.use(relationshipsRouter);
router.use(reviewsRouter);
router.use(institutionalKnowledgeRouter);
router.use(selfImprovementRouter);
router.use(systemEconomicsRouter);
router.use(identityRouter);
router.use(executiveObjectivesRouter);
router.use(organizationalMemoryRouter);
router.use(decisionMemoryRouter);
router.use(authRouter);
router.use(importsRouter);
router.use(timeRouter);
router.use(aiRouter);
router.use(androidRouter);
router.use(backupsRouter);
router.use(orchestrationRouter);
router.use(founderProfileRouter);
router.use(memoryArchitectureRouter);
router.use(curiosityRouter);
router.use(trustRouter);
router.use(strategyRouter);
router.use(learningRouter);
router.use(workspaceRouter);
router.use(constitutionRouter);
router.use(confidenceRouter);
router.use(foundationRouter);

export default router;
