import { Router, type IRouter } from "express";
import healthRouter from "./health";
import understandingRouter from "./understanding";
import reasoningRouter from "./reasoning";
import connectorsRouter from "./connectors";
import costsRouter from "./costs";
import brainVersionsRouter from "./brain-versions";
import schedulerRouter from "./scheduler";
import governanceRouter from "./governance";
import memoryRouter from "./memory";
import graphRouter from "./graph";
import relationshipsRouter from "./relationships";
import reviewsRouter from "./reviews";
import institutionalKnowledgeRouter from "./institutional-knowledge";
import selfImprovementRouter from "./self-improvement";
import systemEconomicsRouter from "./system-economics";
import identityRouter from "./identity";
import executiveObjectivesRouter from "./executive-objectives";
import organizationalMemoryRouter from "./organizational-memory";
import decisionMemoryRouter from "./decision-memory";
import foundationRouter from "./foundation";
import authRouter from "./auth";
import importsRouter from "./imports";

const router: IRouter = Router();

router.use(healthRouter);
router.use(understandingRouter);
router.use(reasoningRouter);
router.use(connectorsRouter);
router.use(costsRouter);
router.use(brainVersionsRouter);
router.use(schedulerRouter);
router.use(governanceRouter);
router.use(memoryRouter);
router.use(graphRouter);
router.use(relationshipsRouter);
router.use(reviewsRouter);
router.use(institutionalKnowledgeRouter);
router.use(selfImprovementRouter);
router.use(systemEconomicsRouter);
router.use(identityRouter);
router.use(executiveObjectivesRouter);
router.use(organizationalMemoryRouter);
router.use(decisionMemoryRouter);
router.use(authRouter);
router.use(importsRouter);
router.use(foundationRouter);

export default router;
